data:
    path: dataset/test/recordings_h5
    mode: gt_test # gtflow_dt1/gtflow_dt4
    window: 100000 # 1 for dt1, 0.25 for dt4
    window_eval: 50000 # not used

model:
    mask_output: True

metrics:
    name: [RSAT]  # FWL, RSAT, AEE
    flow_scaling: 128

loader:
    batch_size: 1
    resolution: [480, 640] # H x W
    augment: []
    gpu: 0

vis:
    enabled: True
    px: 400
    bars: True
    activity: False
    store: False

hot_filter:
    enabled: True
    max_px: 100
    min_obvs: 5
    max_rate: 0.8
