experiment: Default

data:
    path: /data/youssef/datasets/ESIM_h5/oneobject/
    mode: events # events/time
    window: 200000 # events/time
    window_loss: 200000 # events

model:
    name: EVFlowNet_Segmentation # EVFlowNet/*FireFlowNet/*FireNet/E2VID/RecEVFlowNet
    encoding: voxel # voxel/cnt
    round_encoding: False # for voxel encoding
    norm_input: False # normalize input
    num_bins: 5
    base_num_channels: 32
    kernel_size: 3
    activations: [relu, Null] # activations for ff and rec neurons
    mask_output: True

spiking_neuron: Null
    
loss:
    flow_regul_weight: 0.001
    clip_grad: 100.0 # set to Null to disable
    overwrite_intermediate: False

optimizer:
    name: Adam
    lr: 0.00001

loader:
    n_epochs: 5000
    batch_size: 8
    resolution: [480, 640] 
    augment: ["Horizontal", "Vertical", "Polarity"]
    augment_prob: [0.5, 0.5, 0.5]
    gpu: 0

vis:
    verbose: True
    enabled: False
    px: 400
    store_grads: False

hot_filter:
    enabled: False
    max_px: 100
    min_obvs: 5
    max_rate: 0.8
